pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout your Java project from version control
                git 'https://github.com/Kartik9865/JavaCodes.git'
            }
        }
        stage('Compile') {
            steps {
                // Compile your Java code
                sh 'javac -d . *.java'
            }
        }
        stage('Run') {
            steps {
                // Run your Java project
                sh 'java -cp . SingletonClass'
            }
        }
    }
}
